### ISSUE TITLE
Balance Not Adding Up

### ISSUE THREAD

**Issue by ehizdom** [RashminDungrani/online-banking#3]
Hello Greetings
I am trying to use your project for my school work but when i run it on a website, the balance is not adding up and i don't know where to fix that from can you please help me?. and also i am trying to change the inr sign to dollar sign can you also help me on that thank you so much

**Comment by ehizdom** [comment]
it says added but it doesn't sum up

**Comment by RashminDungrani** [comment]
I reinstall my project and it just one database entry problem
In phpmyadmin -> bank_db -> tbl_balance -> SQL : and paste this 
`INSERT INTO tbl_balance (account_no, account_type, balance) VALUES ('338509629', 'SAVING', '99999999');`

and hit Go button

Where 338509629 is admin account number which is static, i just forgot to make it dynamic in manage_balance.php file

You can add an entry to tbl_customers in the database (sql manual entry) with this account number and then you can watch all transactions in the customer site as well with all features.

**Comment by ehizdom** [comment]
Thanks so much 
i got an A
can you tutor me please

**Comment by RashminDungrani** [comment]
Well @ehizdom , this website has quick money transfer, chat between customers, request money and admin basic features.

so use all features and you'll know the functionalities of website.

btw let me know if any problem.

**Comment by 2wixta** [comment]
any idea where i can change the currency to USD? I cant seen to find it
